-- aiDexer database schema (Postgres / Neon via Vercel)
-- Apply once after connecting a database, e.g.:
--   psql "$DATABASE_URL" -f db/schema.sql

-- ---------------------------------------------------------------------------
-- Better Auth tables (generated by `npx auth@latest generate` — included here
-- so the schema is reproducible without running the CLI).
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS "user" (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  "emailVerified" BOOLEAN NOT NULL DEFAULT FALSE,
  image TEXT,
  "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "session" (
  id TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  token TEXT NOT NULL UNIQUE,
  "expiresAt" TIMESTAMP NOT NULL,
  "ipAddress" TEXT,
  "userAgent" TEXT,
  "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "account" (
  id TEXT PRIMARY KEY,
  "userId" TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  "accountId" TEXT NOT NULL,
  "providerId" TEXT NOT NULL,
  "issuer" TEXT,
  "audience" TEXT,
  "accessToken" TEXT,
  "refreshToken" TEXT,
  "idToken" TEXT,
  "accessTokenExpiresAt" TIMESTAMP,
  "refreshTokenExpiresAt" TIMESTAMP,
  scope TEXT,
  password TEXT,
  "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT now()
);

-- Newer better-auth versions write issuer/audience on account rows.
ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "issuer" TEXT;
ALTER TABLE "account" ADD COLUMN IF NOT EXISTS "audience" TEXT;

CREATE TABLE IF NOT EXISTS "verification" (
  id TEXT PRIMARY KEY,
  identifier TEXT NOT NULL,
  value TEXT NOT NULL,
  "expiresAt" TIMESTAMP NOT NULL,
  "createdAt" TIMESTAMP NOT NULL DEFAULT now(),
  "updatedAt" TIMESTAMP NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- aiDexer app tables
-- ---------------------------------------------------------------------------

-- "I use this" votes, deduplicated per voter (user id or coarse IP key)
CREATE TABLE IF NOT EXISTS vote_events (
  id SERIAL PRIMARY KEY,
  tool TEXT NOT NULL,
  voter TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  UNIQUE (tool, voter)
);
CREATE INDEX IF NOT EXISTS idx_vote_events_tool ON vote_events (tool);

-- Crowdsourced "outdated info" reports
CREATE TABLE IF NOT EXISTS flags (
  id SERIAL PRIMARY KEY,
  tool TEXT NOT NULL,
  reason TEXT NOT NULL,
  note TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_flags_tool ON flags (tool);

-- Weekly digest subscribers
CREATE TABLE IF NOT EXISTS subscribers (
  id SERIAL PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT now()
);

-- Per-user bookmarked tools ("personal shortlist")
CREATE TABLE IF NOT EXISTS bookmarks (
  user_id TEXT NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  tool TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, tool)
);
CREATE INDEX IF NOT EXISTS idx_bookmarks_user ON bookmarks (user_id);

-- Per-user saved profile, e.g. "I'm a solo dev" (tailors recommendations)
CREATE TABLE IF NOT EXISTS profiles (
  user_id TEXT PRIMARY KEY REFERENCES "user"(id) ON DELETE CASCADE,
  profile TEXT NOT NULL DEFAULT '',
  updated_at TIMESTAMP NOT NULL DEFAULT now()
);
