export interface AIModel {
  name: string;
  category: string;
  strengths: string[];
  bestFor: string[];
  pricing: string;
  access: string;
  description: string;
  url: string;
}

export const aiDatabase: AIModel[] = [
  {
    name: "ChatGPT (GPT-4)",
    category: "General Purpose",
    strengths: ["Conversational AI", "Complex reasoning", "Code generation", "Creative writing"],
    bestFor: ["General questions", "Coding help", "Writing assistance", "Analysis"],
    pricing: "Free tier available, Paid from $20/month",
    access: "Web, API, Mobile",
    description: "OpenAI's flagship language model, excellent for a wide range of tasks from casual conversation to complex problem-solving.",
    url: "https://chatgpt.com",
  },
  {
    name: "Claude (Anthropic)",
    category: "General Purpose",
    strengths: ["Natural conversation", "Long context", "Analysis", "Safety-focused"],
    bestFor: ["Long documents", "Analysis", "Writing", "Research"],
    pricing: "Free tier available, Paid from $20/month",
    access: "Web, API",
    description: "Anthropic's AI assistant known for natural conversations and ability to handle very long contexts.",
    url: "https://claude.ai",
  },
  {
    name: "GitHub Copilot",
    category: "Coding",
    strengths: ["Code completion", "Multi-language support", "IDE integration", "Real-time suggestions"],
    bestFor: ["Software development", "Code writing", "Debugging", "Learning to code"],
    pricing: "$10/month for individuals",
    access: "IDE extension",
    description: "AI-powered code completion tool that integrates directly with your development environment.",
    url: "https://github.com/features/copilot",
  },
  {
    name: "Midjourney",
    category: "Image Generation",
    strengths: ["High-quality images", "Artistic style", "Creative prompts", "Consistent results"],
    bestFor: ["Art creation", "Design concepts", "Illustrations", "Creative projects"],
    pricing: "$10-120/month",
    access: "Discord, Web",
    description: "Generates high-quality artistic images from text prompts, known for stunning visual results.",
    url: "https://www.midjourney.com",
  },
  {
    name: "DALL-E 3",
    category: "Image Generation",
    strengths: ["Text understanding", "Precise control", "Integration with ChatGPT", "Commercial use"],
    bestFor: ["Marketing images", "Concept art", "Illustrations", "Design work"],
    pricing: "Pay-per-use",
    access: "ChatGPT Plus, API",
    description: "OpenAI's image generation model with excellent text understanding and precise control.",
    url: "https://openai.com/dall-e-3",
  },
  {
    name: "Stable Diffusion",
    category: "Image Generation",
    strengths: ["Open source", "Customizable", "Local running", "Many models"],
    bestFor: ["Image generation", "Fine-tuning", "Custom models", "Privacy"],
    pricing: "Free (self-hosted)",
    access: "Local, Web platforms",
    description: "Open-source image generation model that can be run locally and customized extensively.",
    url: "https://stability.ai",
  },
  {
    name: "Jasper",
    category: "Marketing/Writing",
    strengths: ["Marketing copy", "SEO content", "Brand voice", "Templates"],
    bestFor: ["Marketing teams", "Content creation", "Copywriting", "Blog posts"],
    pricing: "$39/month",
    access: "Web",
    description: "AI writing assistant focused on marketing content and business copywriting.",
    url: "https://www.jasper.ai",
  },
  {
    name: "Copy.ai",
    category: "Marketing/Writing",
    strengths: ["Marketing copy", "Social media", "Email writing", "Templates"],
    bestFor: ["Marketing", "Social media content", "Email campaigns", "Product descriptions"],
    pricing: "Free tier available, Paid from $36/month",
    access: "Web",
    description: "AI copywriter that generates marketing copy and content for businesses.",
    url: "https://www.copy.ai",
  },
  {
    name: "ElevenLabs",
    category: "Audio",
    strengths: ["Voice cloning", "Text-to-speech", "Multiple languages", "Realistic voices"],
    bestFor: ["Voiceovers", "Audiobooks", "Podcasts", "Accessibility"],
    pricing: "Free tier available, Paid from $5/month",
    access: "Web, API",
    description: "Advanced text-to-speech and voice cloning technology with remarkably realistic results.",
    url: "https://elevenlabs.io",
  },
  {
    name: "Whisper (OpenAI)",
    category: "Audio",
    strengths: ["Speech recognition", "Multi-language", "Open source", "Accurate transcription"],
    bestFor: ["Transcription", "Subtitles", "Voice notes", "Language learning"],
    pricing: "Free (open source)",
    access: "Local, API",
    description: "OpenAI's open-source speech recognition system with excellent accuracy across languages.",
    url: "https://openai.com/research/whisper",
  },
  {
    name: "Runway ML",
    category: "Video",
    strengths: ["Video editing", "AI effects", "Green screen", "Motion tracking"],
    bestFor: ["Video creation", "Content creators", "Video editing", "AI effects"],
    pricing: "Free tier available, Paid from $12/month",
    access: "Web",
    description: "AI-powered video editing suite with advanced effects and generation capabilities.",
    url: "https://runwayml.com",
  },
  {
    name: "Synthesia",
    category: "Video",
    strengths: ["AI avatars", "Multiple languages", "No camera needed", "Templates"],
    bestFor: ["Training videos", "Corporate communications", "Marketing videos", "Education"],
    pricing: "$22/month",
    access: "Web",
    description: "Create videos with AI avatars speaking in multiple languages without filming.",
    url: "https://www.synthesia.io",
  },
  {
    name: "Perplexity AI",
    category: "Research",
    strengths: ["Web search", "Citations", "Real-time info", "Multiple sources"],
    bestFor: ["Research", "Fact-checking", "Current events", "Learning"],
    pricing: "Free tier available, Paid from $20/month",
    access: "Web, API",
    description: "AI-powered search engine that provides answers with citations from real-time web sources.",
    url: "https://perplexity.ai",
  },
  {
    name: "Notion AI",
    category: "Productivity",
    strengths: ["Writing assistance", "Summarization", "Brainstorming", "Integration"],
    bestFor: ["Note-taking", "Documentation", "Project management", "Writing"],
    pricing: "$10/month add-on",
    access: "Web, Desktop, Mobile",
    description: "AI assistant integrated into Notion for writing, summarizing, and organizing content.",
    url: "https://www.notion.so/product/ai",
  },
  {
    name: "Grammarly",
    category: "Writing",
    strengths: ["Grammar checking", "Style suggestions", "Tone detection", "Plagiarism check"],
    bestFor: ["Writing improvement", "Emails", "Documents", "Professional writing"],
    pricing: "Free tier available, Paid from $12/month",
    access: "Browser extension, Web, Desktop",
    description: "AI writing assistant that checks grammar, style, and tone across all your writing.",
    url: "https://www.grammarly.com",
  },
  {
    name: "Cursor",
    category: "Coding",
    strengths: ["AI code editor", "Code generation", "Refactoring", "Chat interface"],
    bestFor: ["Software development", "Code editing", "Learning to code", "Debugging"],
    pricing: "Free tier available, Paid from $20/month",
    access: "Desktop app",
    description: "AI-first code editor that helps you write, edit, and understand code faster.",
    url: "https://www.cursor.com",
  },
  {
    name: "Replit AI",
    category: "Coding",
    strengths: ["Code completion", "Chat assistance", "Project generation", "Learning"],
    bestFor: ["Learning to code", "Prototyping", "Web development", "Education"],
    pricing: "Free tier available, Paid from $10/month",
    access: "Web IDE",
    description: "Online IDE with built-in AI assistance for coding and learning programming.",
    url: "https://replit.com",
  },
  {
    name: "Gemini (Google)",
    category: "General Purpose",
    strengths: ["Multimodal", "Google integration", "Long context", "Reasoning"],
    bestFor: ["General questions", "Image analysis", "Google workspace", "Research"],
    pricing: "Free tier available, Paid via API",
    access: "Web, API",
    description: "Google's multimodal AI model with integration across Google's ecosystem.",
    url: "https://gemini.google.com",
  },
  {
    name: "Bing Copilot",
    category: "General Purpose",
    strengths: ["Web search", "Real-time info", "Image generation", "Free access"],
    bestFor: ["Research", "Web queries", "Image creation", "General questions"],
    pricing: "Free",
    access: "Web, Browser",
    description: "Microsoft's AI assistant integrated with Bing search for real-time information.",
    url: "https://copilot.microsoft.com",
  },
  {
    name: "Leonardo AI",
    category: "Image Generation",
    strengths: ["Game assets", "Style variety", "Training data", "Fast generation"],
    bestFor: ["Game development", "Concept art", "Digital art", "Design"],
    pricing: "Free tier available, Paid from $10/month",
    access: "Web",
    description: "AI image generation platform focused on game assets and creative projects.",
    url: "https://leonardo.ai",
  },
  {
    name: "Canva AI",
    category: "Design",
    strengths: ["Templates", "Magic design", "Image generation", "Brand kit"],
    bestFor: ["Graphic design", "Social media", "Presentations", "Marketing materials"],
    pricing: "Free tier available, Paid from $12/month",
    access: "Web, Mobile",
    description: "Design platform with AI tools for creating professional graphics and presentations.",
    url: "https://www.canva.com",
  },
  {
    name: "Figma AI",
    category: "Design",
    strengths: ["UI design", "Prototyping", "Collaboration", "AI features"],
    bestFor: ["UI/UX design", "Web design", "Prototyping", "Team collaboration"],
    pricing: "Free tier available, Paid from $12/month",
    access: "Web, Desktop",
    description: "Collaborative design platform with AI-powered features for UI/UX design.",
    url: "https://www.figma.com",
  },
  {
    name: "Otter.ai",
    category: "Productivity",
    strengths: ["Meeting transcription", "Notes", "Action items", "Integration"],
    bestFor: ["Meetings", "Interviews", "Lectures", "Note-taking"],
    pricing: "Free tier available, Paid from $10/month",
    access: "Web, Mobile",
    description: "AI meeting assistant that transcribes conversations and generates summaries.",
    url: "https://otter.ai",
  },
  {
    name: "Descript",
    category: "Audio",
    strengths: ["Audio editing", "Transcription", "Voice cloning", "Video editing"],
    bestFor: ["Podcasting", "Video production", "Transcription", "Content creation"],
    pricing: "Free tier available, Paid from $12/month",
    access: "Desktop, Web",
    description: "Edit audio and video by editing text, with AI transcription and voice cloning.",
    url: "https://www.descript.com",
  },
  {
    name: "Cohere",
    category: "Enterprise",
    strengths: ["Text generation", "Classification", "Embeddings", "Enterprise focus"],
    bestFor: ["Business applications", "NLP tasks", "Search", "Chatbots"],
    pricing: "Free tier available, Paid via API",
    access: "API",
    description: "Enterprise-focused NLP platform for building AI-powered business applications.",
    url: "https://cohere.com",
  },
  {
    name: "DeepL",
    category: "Language",
    strengths: ["Translation accuracy", "Multiple languages", "Document translation", "API"],
    bestFor: ["Translation", "Localization", "Document translation", "Business communication"],
    pricing: "Free tier available, Paid from $8/month",
    access: "Web, API, Desktop",
    description: "AI translation service known for highly accurate and natural-sounding translations.",
    url: "https://www.deepl.com",
  },
  {
    name: "Murf AI",
    category: "Audio",
    strengths: ["Text-to-speech", "Voice cloning", "Custom voices", "Commercial license"],
    bestFor: ["Voiceovers", "Presentations", "E-learning", "Advertisements"],
    pricing: "Free tier available, Paid from $19/month",
    access: "Web",
    description: "AI voice generator with natural-sounding voices for professional voiceovers.",
    url: "https://murf.ai",
  },
  {
    name: "Tabnine",
    category: "Coding",
    strengths: ["Code completion", "Privacy-focused", "On-premise", "Team learning"],
    bestFor: ["Enterprise development", "Privacy-conscious teams", "Code completion", "IDE integration"],
    pricing: "Free tier available, Paid from $12/month",
    access: "IDE extension",
    description: "AI code completion tool that learns your team's coding patterns while keeping code private.",
    url: "https://www.tabnine.com",
  },
  {
    name: "Typeform AI",
    category: "Productivity",
    strengths: ["Smart forms", "Logic jumps", "Analytics", "Integration"],
    bestFor: ["Surveys", "Lead generation", "Customer feedback", "Quizzes"],
    pricing: "Free tier available, Paid from $25/month",
    access: "Web",
    description: "Interactive form builder with AI-powered logic and analytics.",
    url: "https://www.typeform.com",
  },
  {
    name: "Loom AI",
    category: "Video",
    strengths: ["Screen recording", "AI summaries", "Transcription", "Async communication"],
    bestFor: ["Team communication", "Tutorials", "Feedback", "Documentation"],
    pricing: "Free tier available, Paid from $12/month",
    access: "Web, Desktop, Mobile",
    description: "Video messaging platform with AI-generated summaries and transcriptions.",
    url: "https://www.loom.com",
  },
  {
    name: "Fireflies.ai",
    category: "Productivity",
    strengths: ["Meeting notes", "Transcription", "Action items", "Search"],
    bestFor: ["Meetings", "Sales calls", "Team collaboration", "Note-taking"],
    pricing: "Free tier available, Paid from $10/month",
    access: "Web, Integration",
    description: "AI meeting assistant that records, transcribes, and searches across your meetings.",
    url: "https://fireflies.ai",
  },
  {
    name: "Bard (Google)",
    category: "General Purpose",
    strengths: ["Web access", "Google integration", "Multimodal", "Free"],
    bestFor: ["Research", "Writing", "Brainstorming", "General questions"],
    pricing: "Free",
    access: "Web",
    description: "Google's conversational AI with access to web information and Google services.",
    url: "https://gemini.google.com",
  },
  {
    name: "Codeium",
    category: "Coding",
    strengths: ["Free tier", "Multi-IDE", "Code completion", "Chat"],
    bestFor: ["Students", "Open source", "Code completion", "Learning to code"],
    pricing: "Free for individuals",
    access: "IDE extension",
    description: "Free AI code completion and chat tool supporting multiple IDEs and languages.",
    url: "https://codeium.com",
  },
  {
    name: "Windsurf",
    category: "Coding",
    strengths: ["AI agent", "Code generation", "Cascade", "Multi-file editing"],
    bestFor: ["Software development", "Code editing", "Complex projects", "Debugging"],
    pricing: "Free tier available, Paid from $15/month",
    access: "Desktop app",
    description: "AI-powered code editor with agent capabilities for complex development tasks.",
    url: "https://www.codeium.com/windsurf",
  },
  {
    name: "v0 by Vercel",
    category: "Coding",
    strengths: ["UI generation", "React code", "Tailwind CSS", "Prototyping"],
    bestFor: ["Web development", "UI design", "React projects", "Prototyping"],
    pricing: "Free tier available, Paid from $20/month",
    access: "Web",
    description: "AI tool that generates React UI components from text descriptions.",
    url: "https://v0.dev",
  },
  {
    name: "Beautiful.ai",
    category: "Design",
    strengths: ["Smart templates", "Auto-formatting", "Team collaboration", "Presentations"],
    bestFor: ["Presentations", "Business slides", "Reports", "Team collaboration"],
    pricing: "$12/month",
    access: "Web",
    description: "AI presentation tool that automatically formats slides as you add content.",
    url: "https://www.beautiful.ai",
  },
  {
    name: "Tome",
    category: "Design",
    strengths: ["AI storytelling", "Generative narratives", "3D assets", "Embeds"],
    bestFor: ["Presentations", "Pitches", "Storytelling", "Reports"],
    pricing: "Free tier available, Paid from $8/month",
    access: "Web",
    description: "AI-powered storytelling platform that generates narrative presentations.",
    url: "https://tome.app",
  },
  {
    name: "Gamma",
    category: "Design",
    strengths: ["AI presentations", "Documents", "Web pages", "One-click styling"],
    bestFor: ["Presentations", "Documents", "Pitches", "Reports"],
    pricing: "Free tier available, Paid from $10/month",
    access: "Web",
    description: "Create presentations, documents, and web pages with AI-generated content.",
    url: "https://gamma.app",
  },
  {
    name: "Udio",
    category: "Audio",
    strengths: ["Music generation", "Custom lyrics", "Multiple genres", "High quality"],
    bestFor: ["Music creation", "Content creation", "Background music", "Creative projects"],
    pricing: "Free tier available, Paid from $10/month",
    access: "Web",
    description: "AI music generation platform that creates songs from text descriptions.",
    url: "https://www.udio.com",
  },
  {
    name: "Suno",
    category: "Audio",
    strengths: ["Music generation", "Vocals", "Instrumental", "Multiple styles"],
    bestFor: ["Music creation", "Songwriting", "Content creation", "Entertainment"],
    pricing: "Free tier available, Paid from $10/month",
    access: "Web",
    description: "AI music platform that generates complete songs with vocals and instruments.",
    url: "https://suno.com",
  },
  {
    name: "HeyGen",
    category: "Video",
    strengths: ["AI avatars", "Voice cloning", "Multi-language", "Templates"],
    bestFor: ["Marketing videos", "Training", "Sales", "Localization"],
    pricing: "Free tier available, Paid from $24/month",
    access: "Web",
    description: "AI video generation platform with customizable avatars and voice cloning.",
    url: "https://www.heygen.com",
  },
  {
    name: "Pika Labs",
    category: "Video",
    strengths: ["Video generation", "Style transfer", "Camera controls", "Free tier"],
    bestFor: ["Social media", "Creative videos", "Marketing", "Content creation"],
    pricing: "Free tier available, Paid from $10/month",
    access: "Web",
    description: "AI video generation platform for creating and editing videos from text.",
    url: "https://pika.art",
  },
  {
    name: "Khanmigo (Khan Academy)",
    category: "Education",
    strengths: ["Tutoring", "Personalized learning", "Multiple subjects", "Free"],
    bestFor: ["Students", "Homework help", "Learning", "Test prep"],
    pricing: "Free",
    access: "Web",
    description: "AI tutor from Khan Academy that provides personalized help across subjects.",
    url: "https://www.khanacademy.org/khan-labs",
  },
  {
    name: "Duolingo Max",
    category: "Education",
    strengths: ["Language learning", "AI conversations", "Explanations", "Gamification"],
    bestFor: ["Language learning", "Practice conversations", "Grammar explanations", "Students"],
    pricing: "$6/month (Super tier)",
    access: "Mobile, Web",
    description: "AI-enhanced language learning with conversation practice and explanations.",
    url: "https://www.duolingo.com",
  },
  {
    name: "Consensus",
    category: "Research",
    strengths: ["Academic search", "Paper summaries", "Evidence-based", "Citations"],
    bestFor: ["Research", "Academic papers", "Evidence-based answers", "Students"],
    pricing: "Free tier available, Paid from $11/month",
    access: "Web",
    description: "AI search engine that finds answers from peer-reviewed academic research.",
    url: "https://consensus.app",
  },
  {
    name: "Elicit",
    category: "Research",
    strengths: ["Research automation", "Paper analysis", "Data extraction", "Summaries"],
    bestFor: ["Researchers", "Literature review", "Data extraction", "Academic work"],
    pricing: "Free tier available, Paid from $10/month",
    access: "Web",
    description: "AI research assistant that automates literature reviews and data extraction.",
    url: "https://elicit.org",
  },
  {
    name: "ChatPDF",
    category: "Productivity",
    strengths: ["PDF chat", "Document analysis", "Summaries", "Q&A"],
    bestFor: ["Document review", "Research", "Study", "Legal documents"],
    pricing: "Free tier available, Paid from $5/month",
    access: "Web",
    description: "Chat with any PDF document to extract information and get summaries.",
    url: "https://www.chatpdf.com",
  },
  {
    name: "Phind",
    category: "Coding",
    strengths: ["Developer focused", "Code search", "Explanations", "Web access"],
    bestFor: ["Programming questions", "Debugging", "Code search", "Learning"],
    pricing: "Free",
    access: "Web",
    description: "AI search engine specifically designed for developers and programming questions.",
    url: "https://www.phind.com",
  },
  {
    name: "You.com",
    category: "Research",
    strengths: ["AI search", "Multiple models", "Customizable", "Privacy"],
    bestFor: ["Research", "Web search", "AI chat", "Privacy-conscious users"],
    pricing: "Free tier available, Paid from $15/month",
    access: "Web",
    description: "AI-powered search engine with multiple models and customizable experience.",
    url: "https://you.com",
  },
  {
    name: "Rewind AI",
    category: "Productivity",
    strengths: ["Memory assistant", "Screen recording", "Search", "Privacy"],
    bestFor: ["Personal search", "Meeting recall", "Research", "Productivity"],
    pricing: "Free tier available, Paid from $15/month",
    access: "Desktop app",
    description: "AI that records everything on your device and makes it searchable.",
    url: "https://www.rewind.ai",
  },
  {
    name: "Pi AI",
    category: "General Purpose",
    strengths: ["Emotional support", "Personal", "Conversational", "Free"],
    bestFor: ["Conversation", "Brainstorming", "Emotional support", "Personal assistant"],
    pricing: "Free",
    access: "Web, Mobile",
    description: "Personal AI assistant designed for supportive and meaningful conversations.",
    url: "https://pi.ai",
  },
  {
    name: "Character.AI",
    category: "General Purpose",
    strengths: ["Character chat", "Roleplay", "Creative", "Free"],
    bestFor: ["Entertainment", "Creative writing", "Roleplay", "Character creation"],
    pricing: "Free tier available, Paid from $9/month",
    access: "Web, Mobile",
    description: "Chat with AI characters for entertainment, creativity, and learning.",
    url: "https://character.ai",
  },
  {
    name: "Sora (OpenAI)",
    category: "Video",
    strengths: ["Text-to-video", "High quality", "Realistic", "Long clips"],
    bestFor: ["Video creation", "Marketing", "Content creation", "Storytelling"],
    pricing: "ChatGPT Plus subscription",
    access: "Web",
    description: "OpenAI's text-to-video model that generates realistic videos from descriptions.",
    url: "https://openai.com/sora",
  },
  {
    name: "Grok (xAI)",
    category: "General Purpose",
    strengths: ["Real-time info", "Humor", "X integration", "Uncensored"],
    bestFor: ["Current events", "Research", "Humor", "General questions"],
    pricing: "Free tier available, Paid via X Premium",
    access: "Web, X platform",
    description: "xAI's chatbot with real-time information and integration with X platform.",
    url: "https://grok.x.ai",
  },
  {
    name: "Mistral AI",
    category: "Enterprise",
    strengths: ["Open source", "Multilingual", "Efficient", "API"],
    bestFor: ["Multilingual apps", "Open source projects", "API integration", "Research"],
    pricing: "Free tier available, Paid via API",
    access: "Web, API",
    description: "European AI company offering powerful open-source language models.",
    url: "https://mistral.ai",
  },
  {
    name: "Poe (Quora)",
    category: "General Purpose",
    strengths: ["Multiple models", "Model comparison", "Custom bots", "Free tier"],
    bestFor: ["Model comparison", "Chat", "Custom bots", "Research"],
    pricing: "Free tier available, Paid from $19/month",
    access: "Web, Mobile",
    description: "Platform to access and compare multiple AI models in one place.",
    url: "https://poe.com",
  },
  {
    name: "Meta AI",
    category: "General Purpose",
    strengths: ["Free", "Multimodal", "WhatsApp integration", "Image generation"],
    bestFor: ["General questions", "Image generation", "Social media", "Free AI"],
    pricing: "Free",
    access: "Web, WhatsApp, Instagram",
    description: "Meta's AI assistant integrated across Facebook, WhatsApp, and Instagram.",
    url: "https://www.meta.ai",
  },
  {
    name: "Adobe Firefly",
    category: "Image Generation",
    strengths: ["Commercial safe", "Adobe integration", "Style transfer", "Text effects"],
    bestFor: ["Design", "Marketing", "Commercial use", "Photo editing"],
    pricing: "Free tier available, Paid from $5/month",
    access: "Web, Adobe apps",
    description: "Adobe's commercially-safe AI image generation integrated with Creative Cloud.",
    url: "https://firefly.adobe.com",
  },
  {
    name: "Remove.bg",
    category: "Image Generation",
    strengths: ["Background removal", "Fast", "API", "Batch processing"],
    bestFor: ["Photo editing", "E-commerce", "Marketing", "Design"],
    pricing: "Free tier available, Pay-per-use",
    access: "Web, API",
    description: "AI tool that automatically removes backgrounds from images.",
    url: "https://www.remove.bg",
  },
  {
    name: "Ideogram",
    category: "Image Generation",
    strengths: ["Text in images", "Typography", "Free tier", "Accurate text"],
    bestFor: ["Logos", "Posters", "Marketing", "Design with text"],
    pricing: "Free tier available, Paid from $8/month",
    access: "Web",
    description: "AI image generator that excels at rendering accurate text in images.",
    url: "https://ideogram.ai",
  },
  {
    name: "Playground AI",
    category: "Image Generation",
    strengths: ["Free tier", "Filters", "Canvas", "Style variety"],
    bestFor: ["Art creation", "Design", "Social media", "Creative projects"],
    pricing: "Free tier available, Paid from $15/month",
    access: "Web",
    description: "AI image generation platform with canvas editing and style filters.",
    url: "https://playground.ai",
  },
  {
    name: "Craiyon",
    category: "Image Generation",
    strengths: ["Free", "Unlimited", "Simple", "No account needed"],
    bestFor: ["Quick images", "Ideas", "Fun", "Experimentation"],
    pricing: "Free",
    access: "Web",
    description: "Free AI image generator that creates images from text with unlimited generations.",
    url: "https://www.craiyon.com",
  },
  {
    name: "ComfyUI",
    category: "Image Generation",
    strengths: ["Open source", "Node-based", "Customizable", "Local"],
    bestFor: ["Advanced users", "Custom workflows", "Local generation", "Research"],
    pricing: "Free",
    access: "Desktop app",
    description: "Open-source node-based interface for Stable Diffusion workflows.",
    url: "https://www.comfy.org",
  },
  {
    name: "Zapier AI",
    category: "Automation",
    strengths: ["Workflow automation", "App integrations", "AI actions", "No-code"],
    bestFor: ["Connecting apps", "Automating tasks", "Chatbots", "Data routing"],
    pricing: "Free tier available, Paid from $20/month",
    access: "Web",
    description: "Automate work across 6,000+ apps with AI-powered workflows and built-in AI actions.",
    url: "https://zapier.com/ai",
  },
  {
    name: "Quizlet AI",
    category: "Education",
    strengths: ["Flashcards", "Practice tests", "Learn mode", "AI explanations"],
    bestFor: ["Studying", "Exam prep", "Memorization", "Homework help"],
    pricing: "Free tier available, Paid from $8/month",
    access: "Web, Mobile",
    description: "AI-powered study tool with flashcards, practice tests, and step-by-step homework explanations.",
    url: "https://quizlet.com",
  },
  {
    name: "Zoom AI Companion",
    category: "Productivity",
    strengths: ["Meeting summaries", "In-meeting questions", "Action items", "Smart recordings"],
    bestFor: ["Meetings", "Team collaboration", "Recap notes"],
    pricing: "Included with paid Zoom plans",
    access: "Zoom app",
    description: "Zoom's built-in AI assistant that summarizes meetings, drafts messages, and answers questions about your meetings.",
    url: "https://www.zoom.com/en/ai-assistant/",
  },
  {
    name: "Calendly AI",
    category: "Business",
    strengths: ["Scheduling", "Meeting automation", "Routing forms", "Reminders"],
    bestFor: ["Booking meetings", "Sales calls", "Team scheduling"],
    pricing: "Free tier available, Paid from $10/seat/month",
    access: "Web",
    description: "AI-assisted scheduling that finds the best meeting times and automates booking workflows.",
    url: "https://calendly.com",
  },
  {
    name: "OpenRefine",
    category: "Data & Analytics",
    strengths: ["Data cleaning", "CSV handling", "Open source", "Local running"],
    bestFor: ["Cleaning messy data", "CSV & Excel fixes", "Transforming datasets", "Privacy"],
    pricing: "Free (open source)",
    access: "Local, Desktop, Browser",
    description: "A free, open-source desktop tool for cleaning, transforming, and reconciling messy CSV and spreadsheet data offline with no API limits.",
    url: "https://openrefine.org",
  },
  {
    name: "PandasAI",
    category: "Data & Analytics",
    strengths: ["Natural language queries", "Python & pandas", "Open source", "Local"],
    bestFor: ["Analyzing CSVs with plain English", "Data analysis", "Reports", "Privacy"],
    pricing: "Free (open source)",
    access: "Local, Python library",
    description: "Open-source library that wraps pandas so you can ask questions about your CSV and tabular data in plain English, fully local and offline.",
    url: "https://github.com/sinaptik-ai/pandas-ai",
  },
  {
    name: "Row Zero",
    category: "Data & Analytics",
    strengths: ["Spreadsheet", "AI data analysis", "Collaboration", "CSV import"],
    bestFor: ["Analyzing large CSV files", "Spreadsheets", "Data work", "Teams"],
    pricing: "Free tier available, Paid from $15/month",
    access: "Web",
    description: "An AI-powered spreadsheet built for large messy CSV and Excel files, with natural-language formulas and analysis without hitting chat-window limits.",
    url: "https://rowzero.io",
  },
  {
    name: "Julius AI",
    category: "Data & Analytics",
    strengths: ["Data analysis", "Charts and graphs", "CSV & Excel", "Python under the hood"],
    bestFor: ["Cleaning and analyzing CSVs", "Visualizing data", "Reports", "Non-coders"],
    pricing: "$20/month",
    access: "Web",
    description: "Analyzes messy CSV, Excel, and other data files with natural language, generating charts and statistics — great for people who can't code.",
    url: "https://julius.ai",
  },
  {
    name: "Tableau",
    category: "Data & Analytics",
    strengths: ["Business analytics", "Dashboards", "Visualization", "Enterprise"],
    bestFor: ["Dashboards", "Business intelligence", "Large datasets", "Teams"],
    pricing: "$75/month",
    access: "Web, Desktop",
    description: "A leading business-intelligence platform for powerful dashboards and analytics on complex datasets, aimed at analysts and enterprises.",
    url: "https://www.tableau.com",
  },
];
