export interface AIModel {
  name: string;
  category: string;
  strengths: string[];
  bestFor: string[];
  pricing: string;
  access: string;
  description: string;
  url: string;
}

export const aiDatabase: AIModel[] = [
  {
    name: "ChatGPT (OpenAI)",
    category: "General Purpose",
    strengths: ["Conversational AI","Complex reasoning","Code generation","Creative writing"],
    bestFor: ["General questions","Coding help","Writing assistance","Analysis"],
    pricing: "Free tier available, Paid from $20/month",
    access: "Web, API, Mobile",
    description: "OpenAI's flagship AI assistant (current GPT-5 series), excellent for conversation, coding, writing, and analysis.",
    url: "https://chatgpt.com",
  },
  {
    name: "Claude (Anthropic)",
    category: "General Purpose",
    strengths: ["Natural conversation","Long context","Analysis","Safety-focused"],
    bestFor: ["Long documents","Analysis","Writing","Research"],
    pricing: "Free tier available, Paid from $20/month",
    access: "Web, API",
    description: "Anthropic's AI assistant known for natural conversations and ability to handle very long contexts.",
    url: "https://claude.ai",
  },
  {
    name: "GitHub Copilot",
    category: "Coding",
    strengths: ["Code completion","Multi-language support","IDE integration","Real-time suggestions"],
    bestFor: ["Software development","Code writing","Debugging","Learning to code"],
    pricing: "Free tier available, Paid from $10/month (Pro)",
    access: "IDE extension",
    description: "AI-powered code completion tool that integrates directly with your development environment.",
    url: "https://github.com/features/copilot",
  },
  {
    name: "Midjourney",
    category: "Image Generation",
    strengths: ["High-quality images","Artistic style","Creative prompts","Consistent results"],
    bestFor: ["Art creation","Design concepts","Illustrations","Creative projects"],
    pricing: "$10 / $30 / $60 / $120 per month",
    access: "Discord, Web",
    description: "Generates high-quality artistic images from text prompts, known for stunning visual results.",
    url: "https://www.midjourney.com",
  },
  {
    name: "DALL-E 3",
    category: "Image Generation",
    strengths: ["Text understanding","Precise control","Integration with ChatGPT","Commercial use"],
    bestFor: ["Marketing images","Concept art","Illustrations","Design work"],
    pricing: "Pay-per-use",
    access: "ChatGPT Plus, API",
    description: "OpenAI's image generation model with excellent text understanding and precise control.",
    url: "https://openai.com/dall-e-3",
  },
  {
    name: "Stable Diffusion",
    category: "Image Generation",
    strengths: ["Open source","Customizable","Local running","Many models"],
    bestFor: ["Image generation","Fine-tuning","Custom models","Privacy"],
    pricing: "Free (self-hosted)",
    access: "Local, Web platforms",
    description: "Open-source image generation model that can be run locally and customized extensively.",
    url: "https://stability.ai",
  },
  {
    name: "Jasper",
    category: "Marketing/Writing",
    strengths: ["Marketing copy","SEO content","Brand voice","Templates"],
    bestFor: ["Marketing teams","Content creation","Copywriting","Social media"],
    pricing: "$49-125/month",
    access: "Web",
    description: "AI writing assistant specifically designed for marketing teams and content creators.",
    url: "https://www.jasper.ai",
  },
  {
    name: "Notion AI",
    category: "Productivity",
    strengths: ["Note-taking integration","Summarization","Writing assistance","Organization"],
    bestFor: ["Note-taking","Documentation","Meeting notes","Knowledge management"],
    pricing: "$10/month add-on",
    access: "Notion workspace",
    description: "AI assistant integrated directly into Notion for enhanced productivity and document management.",
    url: "https://www.notion.so/product/ai",
  },
  {
    name: "Perplexity AI",
    category: "Research",
    strengths: ["Real-time web search","Citation sources","Research accuracy","Up-to-date info"],
    bestFor: ["Research","Fact-checking","Current events","Academic work"],
    pricing: "Free tier available, Paid from $20/month",
    access: "Web, API",
    description: "AI-powered search engine that provides cited sources and real-time information.",
    url: "https://www.perplexity.ai",
  },
  {
    name: "Runway",
    category: "Video",
    strengths: ["Video generation","Video editing","AI effects","Professional tools"],
    bestFor: ["Video creation","Content creation","Film production","Marketing videos"],
    pricing: "$12-76/month",
    access: "Web",
    description: "Professional AI video generation and editing platform for content creators.",
    url: "https://runwayml.com",
  },
  {
    name: "ElevenLabs",
    category: "Audio",
    strengths: ["Voice cloning","Text-to-speech","Natural voices","Multi-language"],
    bestFor: ["Voiceovers","Audiobooks","Content creation","Accessibility"],
    pricing: "Free tier available, Paid from $5/month",
    access: "Web, API",
    description: "Advanced text-to-speech and voice cloning platform with incredibly natural-sounding voices.",
    url: "https://elevenlabs.io",
  },
  {
    name: "Cursor",
    category: "Coding",
    strengths: ["AI-powered IDE","Code understanding","Debugging","Chat with codebase"],
    bestFor: ["Software development","Code review","Learning codebases","Refactoring"],
    pricing: "Free tier available, Paid from $20/month",
    access: "IDE",
    description: "AI-first code editor that understands your entire codebase and helps with development tasks.",
    url: "https://cursor.com",
  },
  {
    name: "Gamma",
    category: "Presentations",
    strengths: ["Slide generation","Design automation","Content creation","Templates"],
    bestFor: ["Presentations","Pitch decks","Marketing materials","Reports"],
    pricing: "Free tier available, Paid from $10/month",
    access: "Web",
    description: "AI-powered presentation builder that creates beautiful slides from simple prompts.",
    url: "https://gamma.app",
  },
  {
    name: "Hugging Face",
    category: "Development Platform",
    strengths: ["Model hub","Open source","Custom models","Community"],
    bestFor: ["ML development","Model deployment","Research","Custom solutions"],
    pricing: "Free (mostly), Paid compute",
    access: "Web, API",
    description: "Platform for sharing and using open-source machine learning models and tools.",
    url: "https://huggingface.co",
  },
  {
    name: "Gemini Advanced",
    category: "General Purpose",
    strengths: ["Multimodal","Long context","Google integration","Reasoning"],
    bestFor: ["General questions","Coding","Research","Multimodal tasks"],
    pricing: "Free tier available, Paid from $19.99/month",
    access: "Web, Mobile, API",
    description: "Google's flagship multimodal AI model with deep integration across Google services and powerful reasoning.",
    url: "https://gemini.google.com",
  },
  {
    name: "Microsoft Copilot",
    category: "General Purpose",
    strengths: ["Microsoft 365 integration","Web search","Chat","Copilot Studio"],
    bestFor: ["Office work","Everyday questions","Productivity","Content creation"],
    pricing: "Free tier, Paid from $20/month",
    access: "Web, Windows, Mobile",
    description: "Microsoft's AI assistant woven into Windows and Microsoft 365, great for everyday productivity.",
    url: "https://copilot.microsoft.com",
  },
  {
    name: "Grok (xAI)",
    category: "General Purpose",
    strengths: ["Real-time data","Humorous style","X integration","Conversation"],
    bestFor: ["Real-time topics","Casual conversation","News","General questions"],
    pricing: "Free tier available, Paid from $8/month",
    access: "Web, X platform",
    description: "xAI's assistant with real-time knowledge and a distinctive conversational personality.",
    url: "https://x.ai/grok",
  },
  {
    name: "Mistral Large",
    category: "General Purpose",
    strengths: ["Reasoning","Multilingual","Strong logic","API access"],
    bestFor: ["Complex reasoning","Multilingual tasks","Enterprise","Coding"],
    pricing: "Pay-per-use API",
    access: "API, Web (Le Chat)",
    description: "Mistral AI's high-capability large model offering strong reasoning and multilingual performance.",
    url: "https://mistral.ai",
  },
  {
    name: "Replit Agent",
    category: "Coding",
    strengths: ["Full-stack building","Deployment","IDE","Autonomous agents"],
    bestFor: ["App building","Prototyping","Full-stack dev","Deployment"],
    pricing: "Free tier, Paid from $20/month",
    access: "Web IDE",
    description: "An AI agent inside Replit that builds and deploys full applications from natural language prompts.",
    url: "https://replit.com",
  },
  {
    name: "Windsurf",
    category: "Coding",
    strengths: ["Agentic IDE","Code intelligence","Multi-file edits","Cascade agent"],
    bestFor: ["Software development","Refactoring","Code review","Learning codebases"],
    pricing: "Free tier, Paid from $15/month",
    access: "IDE",
    description: "An agentic AI code editor offering deep codebase understanding and multi-file editing.",
    url: "https://windsurf.com",
  },
  {
    name: "Tabnine",
    category: "Coding",
    strengths: ["Code completion","Privacy-first","Models trained on OSS","IDE support"],
    bestFor: ["Code completion","Enterprise dev","Productivity","Multi-language"],
    pricing: "Free tier, Paid from $9/month",
    access: "IDE extension",
    description: "A privacy-focused AI code completion assistant widely used across IDEs and enterprises.",
    url: "https://www.tabnine.com",
  },
  {
    name: "Ideogram",
    category: "Image Generation",
    strengths: ["Text rendering","Typography","Style control","Quality images"],
    bestFor: ["Logos","Text in images","Posters","Design assets"],
    pricing: "Free tier, Paid from $8/month",
    access: "Web, API",
    description: "An image generator known for excellent text rendering and typographic accuracy in images.",
    url: "https://ideogram.ai",
  },
  {
    name: "Leonardo AI",
    category: "Image Generation",
    strengths: ["Fine-tuned models","Style presets","High resolution","Creative control"],
    bestFor: ["Game art","Concept art","Assets","Creative projects"],
    pricing: "Free tier, Paid from $12/month",
    access: "Web, API",
    description: "An image generation platform with fine-tuned models and strong creative controls for artists.",
    url: "https://leonardo.ai",
  },
  {
    name: "Adobe Firefly",
    category: "Image Generation",
    strengths: ["Creative Suite integration","Commercially safe","Style variety","Editing"],
    bestFor: ["Design","Marketing","Photography edits","Creative work"],
    pricing: "Paid via Creative Cloud credit",
    access: "Web, Adobe apps",
    description: "Adobe's generative AI for images designed for commercial safety and Creative Cloud workflows.",
    url: "https://firefly.adobe.com",
  },
  {
    name: "Writesonic",
    category: "Marketing/Writing",
    strengths: ["SEO content","Article writer","Ads copy","Templates"],
    bestFor: ["Blog posts","SEO","Ads","Social media"],
    pricing: "Free tier, Paid from $16/month",
    access: "Web, API",
    description: "An AI writing tool focused on SEO-optimized articles and marketing copy at scale.",
    url: "https://writesonic.com",
  },
  {
    name: "Copy.ai",
    category: "Marketing/Writing",
    strengths: ["Copy generation","Workflows","Brand voice","Go-to-market"],
    bestFor: ["Marketing copy","Sales","Emails","Brand campaigns"],
    pricing: "Free tier, Paid from $36/month",
    access: "Web, API",
    description: "An AI copywriting platform helping marketing teams generate on-brand content and workflows.",
    url: "https://www.copy.ai",
  },
  {
    name: "Grammarly",
    category: "Marketing/Writing",
    strengths: ["Grammar checking","Tone adjustment","Rewrite","Clarity"],
    bestFor: ["Polishing writing","Emails","Documents","Academic work"],
    pricing: "Free tier, Premium from $12/month",
    access: "Web, Browser, Word",
    description: "AI writing assistant for grammar, clarity, tone, and style improvements across many platforms.",
    url: "https://www.grammarly.com",
  },
  {
    name: "Rytr",
    category: "Marketing/Writing",
    strengths: ["Affordable","Tone selection","Use cases","Multi-language"],
    bestFor: ["Copywriting","Blogs","Emails","Product descriptions"],
    pricing: "Free tier, Paid from $9/month",
    access: "Web",
    description: "A budget-friendly AI writing assistant covering many copywriting use cases and languages.",
    url: "https://rytr.me",
  },
  {
    name: "Otter AI",
    category: "Productivity",
    strengths: ["Meeting transcription","Live captions","Summaries","Integration"],
    bestFor: ["Meeting notes","Transcription","Interviews","Action items"],
    pricing: "Free tier, Paid from $16.99/month",
    access: "Web, Zoom, Mobile",
    description: "AI meeting assistant that records, transcribes, and summarizes conversations in real time.",
    url: "https://otter.ai",
  },
  {
    name: "Zapier AI",
    category: "Productivity",
    strengths: ["Automation","App integrations","AI steps","Workflows"],
    bestFor: ["Automation","Workflows","Data sync","Business processes"],
    pricing: "Free tier, Paid from $19.99/month",
    access: "Web",
    description: "Automation platform with AI steps that connect thousands of apps to streamline workflows.",
    url: "https://zapier.com",
  },
  {
    name: "Mem",
    category: "Productivity",
    strengths: ["Self-organizing notes","AI tagging","Search","Knowledge base"],
    bestFor: ["Note-taking","Knowledge management","Personal CRM","Research notes"],
    pricing: "Free tier, Paid from $14.99/month",
    access: "Web, Mobile",
    description: "A self-organizing AI note and knowledge management app that automatically structures your notes.",
    url: "https://get.mem.ai",
  },
  {
    name: "Superhuman AI",
    category: "Productivity",
    strengths: ["Email triage","Drafting","Smart replies","Speed"],
    bestFor: ["Email management","Inbox zero","Drafting","Executive work"],
    pricing: "$30/month",
    access: "Desktop, Mobile",
    description: "A high-speed email client with AI features for drafting, triage, and achieving inbox zero.",
    url: "https://superhuman.com",
  },
  {
    name: "Elicit",
    category: "Research",
    strengths: ["Literature review","Data extraction","Papers","Research tasks"],
    bestFor: ["Academic research","Literature reviews","Systematic reviews","Evidence gathering"],
    pricing: "Free tier, Paid from $12/month",
    access: "Web",
    description: "An AI research assistant that helps find and analyze academic papers using natural language.",
    url: "https://elicit.com",
  },
  {
    name: "Consensus",
    category: "Research",
    strengths: ["Evidence-based answers","Paper search","Citations","Claim insights"],
    bestFor: ["Fact-checking","Research","Debate evidence","Academic writing"],
    pricing: "Free tier, Premium from $8.99/month",
    access: "Web",
    description: "A search engine that taps into a large academic corpus to answer questions with cited evidence.",
    url: "https://consensus.app",
  },
  {
    name: "Scite",
    category: "Research",
    strengths: ["Citation context","Smart citations","Reference checks","Papers"],
    bestFor: ["Citation analysis","Literature review","Academic writing","Verification"],
    pricing: "Free tier, Paid from $20/month",
    access: "Web",
    description: "A platform that shows how papers are cited and whether findings are supported, for better research.",
    url: "https://scite.ai",
  },
  {
    name: "SciSpace",
    category: "Research",
    strengths: ["Paper interpretation","Math parsing","Paraphrasing","Literature tools"],
    bestFor: ["Reading papers","Understanding research","Citations","Study support"],
    pricing: "Free tier, Paid from $20/month",
    access: "Web, Chrome",
    description: "An AI tool that helps read, interpret, and navigate academic papers and complex scientific text.",
    url: "https://scispace.com",
  },
  {
    name: "Synthesia",
    category: "Video",
    strengths: ["AI avatars","Video generation","Script to video","60+ languages"],
    bestFor: ["Training videos","Corporate comms","Explainer videos","L&D"],
    pricing: "Free tier available, Paid from $29/month (Starter)",
    access: "Web, API",
    description: "Platform for creating professional videos with AI avatars from simple scripts in many languages.",
    url: "https://www.synthesia.io",
  },
  {
    name: "HeyGen",
    category: "Video",
    strengths: ["Avatar videos","Voice cloning","Translation","Talking heads"],
    bestFor: ["Marketing videos","Product demos","Localization","Content creation"],
    pricing: "Free tier, Paid from $29/month",
    access: "Web",
    description: "AI video platform for generating realistic talking-head videos and translating content.",
    url: "https://www.heygen.com",
  },
  {
    name: "Pika",
    category: "Video",
    strengths: ["Text-to-video","Effects","Stylization","Fast generation"],
    bestFor: ["Short clips","Creative effects","Social content","Prototyping"],
    pricing: "Free tier, Premium from $8/month",
    access: "Web, Discord",
    description: "A fast AI video generator turning text prompts into stylized short video clips.",
    url: "https://pika.art",
  },
  {
    name: "CapCut",
    category: "Video",
    strengths: ["AI editing","Auto captions","Templates","Mobile"],
    bestFor: ["Short-form video","Social media","Quick edits","TikTok"],
    pricing: "Free with premium options",
    access: "Web, Mobile, Desktop",
    description: "A popular video editor with AI features like auto captions and one-tap effects.",
    url: "https://www.capcut.com",
  },
  {
    name: "Descript",
    category: "Audio",
    strengths: ["Podcast editing","Text-based editing","Overdub","Transcription"],
    bestFor: ["Podcasts","Audio editing","Video editing","Transcription"],
    pricing: "Free tier, Paid from $12/month",
    access: "Web, Desktop",
    description: "AI audio and video editor that lets you edit media by editing text transcripts.",
    url: "https://www.descript.com",
  },
  {
    name: "Murf",
    category: "Audio",
    strengths: ["Text-to-speech","Studio voices","Voiceover","Fine control"],
    bestFor: ["Voiceovers","eLearning","Ads","Presentations"],
    pricing: "Free tier, Paid from $19/month",
    access: "Web",
    description: "An AI voice generator with studio-quality voices for voiceovers and commercial use.",
    url: "https://murf.ai",
  },
  {
    name: "Suno",
    category: "Audio",
    strengths: ["Music generation","Songwriting","Lyrics","Vocal tracks"],
    bestFor: ["Original music","Songs","Background music","Creative projects"],
    pricing: "Free tier, Paid from $10/month",
    access: "Web, iOS",
    description: "An AI music generator that creates original songs from text descriptions and prompts.",
    url: "https://suno.com",
  },
  {
    name: "Play.ht",
    category: "Audio",
    strengths: ["Text-to-speech","Voice cloning","Realistic voices","API"],
    bestFor: ["Audiobooks","Voiceovers","Assistants","Content generation"],
    pricing: "Free tier, Paid from $29.25/month",
    access: "Web, API",
    description: "Realistic AI text-to-speech and voice cloning platform with a large voice library.",
    url: "https://play.ht",
  },
  {
    name: "Beautiful.ai",
    category: "Presentations",
    strengths: ["Auto-design","Smart templates","Brand consistency","Live editing"],
    bestFor: ["Slick decks","Business presentations","Reports","Pitch decks"],
    pricing: "Free trial, Paid from $12/month",
    access: "Web",
    description: "A presentation tool that auto-designs slides so decks stay consistent and polished.",
    url: "https://www.beautiful.ai",
  },
  {
    name: "Pitch",
    category: "Presentations",
    strengths: ["Team collaboration","Analytics","Templates","Design"],
    bestFor: ["Team decks","Startup pitches","Collaboration","Analytics"],
    pricing: "Free tier, Paid from $20/month",
    access: "Web",
    description: "A collaborative presentation platform with analytics and flexible team features.",
    url: "https://pitch.com",
  },
  {
    name: "SlidesAI",
    category: "Presentations",
    strengths: ["Slides from text","Google Slides add-in","Templates","Speed"],
    bestFor: ["Quick decks","Lecture slides","Reports","Presentations"],
    pricing: "Free tier, Paid from $10/month",
    access: "Google Slides add-in",
    description: "An AI add-in that turns text into ready-to-use Google Slides presentations instantly.",
    url: "https://www.slidesai.io",
  },
  {
    name: "Replicate",
    category: "Development Platform",
    strengths: ["Model hosting","API access","Many models","Cloud inference"],
    bestFor: ["Model deployment","Prototyping","APIs","AI apps"],
    pricing: "Pay-per-use",
    access: "API, Web",
    description: "A cloud platform to run and host open-source AI models behind simple APIs.",
    url: "https://replicate.com",
  },
  {
    name: "Modal",
    category: "Development Platform",
    strengths: ["Serverless compute","GPU","Python","Scaling"],
    bestFor: ["ML pipelines","GPU workloads","Batch jobs","Deployment"],
    pricing: "Pay-per-use",
    access: "SDK, API",
    description: "Serverless cloud platform for running GPU-heavy AI and ML workloads in Python.",
    url: "https://modal.com",
  },
  {
    name: "LangChain",
    category: "Development Platform",
    strengths: ["LLM framework","Agent building","Tooling","Integrations"],
    bestFor: ["LLM apps","Agents","RAG","Developer tooling"],
    pricing: "OSS, Paid cloud",
    access: "Library, API",
    description: "A framework for building LLM-powered applications, agents, and retrieval pipelines.",
    url: "https://www.langchain.com",
  },
  {
    name: "Together AI",
    category: "Development Platform",
    strengths: ["Model inference","Fine-tuning","GPU cloud","Open models"],
    bestFor: ["Model serving","Fine-tuning","AI apps","Research"],
    pricing: "Pay-per-use",
    access: "API, Cloud",
    description: "A cloud platform for running, fine-tuning, and serving open-source AI models.",
    url: "https://www.together.ai",
  },
  {
    name: "OpenRefine",
    category: "Data & Analytics",
    strengths: ["Data cleaning","CSV handling","Open source","Local running"],
    bestFor: ["Cleaning messy data","CSV & Excel fixes","Transforming datasets","Privacy"],
    pricing: "Free (open source)",
    access: "Local, Desktop, Browser",
    description: "A free, open-source desktop tool for cleaning, transforming, and reconciling messy CSV and spreadsheet data offline with no API limits.",
    url: "https://openrefine.org",
  },
  {
    name: "PandasAI",
    category: "Data & Analytics",
    strengths: ["Natural language queries","Python & pandas","Open source","Local"],
    bestFor: ["Analyzing CSVs with plain English","Data analysis","Reports","Privacy"],
    pricing: "Free (open source)",
    access: "Local, Python library",
    description: "Open-source library that wraps pandas so you can ask questions about your CSV and tabular data in plain English, fully local and offline.",
    url: "https://github.com/sinaptik-ai/pandas-ai",
  },
  {
    name: "Row Zero",
    category: "Data & Analytics",
    strengths: ["Spreadsheet","AI data analysis","Collaboration","CSV import"],
    bestFor: ["Analyzing large CSV files","Spreadsheets","Data work","Teams"],
    pricing: "Free tier available, Paid from $15/month",
    access: "Web",
    description: "An AI-powered spreadsheet built for large messy CSV and Excel files, with natural-language formulas and analysis without hitting chat-window limits.",
    url: "https://rowzero.io",
  },
  {
    name: "Julius AI",
    category: "Data & Analytics",
    strengths: ["Data analysis","Charts and graphs","CSV & Excel","Python under the hood"],
    bestFor: ["Cleaning and analyzing CSVs","Visualizing data","Reports","Non-coders"],
    pricing: "$20/month",
    access: "Web",
    description: "Analyzes messy CSV, Excel, and other data files with natural language, generating charts and statistics — great for people who can't code.",
    url: "https://julius.ai",
  },
  {
    name: "Tableau",
    category: "Data & Analytics",
    strengths: ["Business analytics","Dashboards","Visualization","Enterprise"],
    bestFor: ["Dashboards","Business intelligence","Large datasets","Teams"],
    pricing: "$75/month",
    access: "Web, Desktop",
    description: "A leading business-intelligence platform for powerful dashboards and analytics on complex datasets, aimed at analysts and enterprises.",
    url: "https://www.tableau.com",
  },
  {
    name: "Whisper",
    category: "Audio",
    strengths: ["Speech recognition","Multi-language","Open source","Accurate transcription"],
    bestFor: ["Transcription","Subtitles","Voice notes","Language learning"],
    pricing: "Free (open source)",
    access: "Local, API",
    description: "OpenAI's open-source speech recognition system with excellent accuracy across languages.",
    url: "https://openai.com/research/whisper",
  },
  {
    name: "Canva AI",
    category: "Design",
    strengths: ["Templates","Magic design","Image generation","Brand kit"],
    bestFor: ["Graphic design","Social media","Presentations","Marketing materials"],
    pricing: "Free tier available, Paid from $12/month",
    access: "Web, Mobile",
    description: "Design platform with AI tools for creating professional graphics and presentations.",
    url: "https://www.canva.com",
  },
  {
    name: "Figma AI",
    category: "Design",
    strengths: ["UI design","Prototyping","Collaboration","AI features"],
    bestFor: ["UI/UX design","Web design","Prototyping","Team collaboration"],
    pricing: "Free tier available, Paid from $12/month",
    access: "Web, Desktop",
    description: "Collaborative design platform with AI-powered features for UI/UX design.",
    url: "https://www.figma.com",
  },
  {
    name: "Cohere",
    category: "Enterprise",
    strengths: ["Text generation","Classification","Embeddings","Enterprise focus"],
    bestFor: ["Business applications","NLP tasks","Search","Chatbots"],
    pricing: "Free tier available, Paid via API",
    access: "API",
    description: "Enterprise-focused NLP platform for building AI-powered business applications.",
    url: "https://cohere.com",
  },
  {
    name: "DeepL",
    category: "Language",
    strengths: ["Translation accuracy","Multiple languages","Document translation","API"],
    bestFor: ["Translation","Localization","Document translation","Business communication"],
    pricing: "Free tier available, Paid from $8/month",
    access: "Web, API, Desktop",
    description: "AI translation service known for highly accurate and natural-sounding translations.",
    url: "https://www.deepl.com",
  },
  {
    name: "Typeform AI",
    category: "Productivity",
    strengths: ["Smart forms","Logic jumps","Analytics","Integration"],
    bestFor: ["Surveys","Lead generation","Customer feedback","Quizzes"],
    pricing: "Free tier available, Paid from $25/month",
    access: "Web",
    description: "Interactive form builder with AI-powered logic and analytics.",
    url: "https://www.typeform.com",
  },
  {
    name: "Loom AI",
    category: "Video",
    strengths: ["Screen recording","AI summaries","Transcription","Async communication"],
    bestFor: ["Team communication","Tutorials","Feedback","Documentation"],
    pricing: "Free tier available, Paid from $12/month",
    access: "Web, Desktop, Mobile",
    description: "Video messaging platform with AI-generated summaries and transcriptions.",
    url: "https://www.loom.com",
  },
  {
    name: "Fireflies.ai",
    category: "Productivity",
    strengths: ["Meeting notes","Transcription","Action items","Search"],
    bestFor: ["Meetings","Sales calls","Team collaboration","Note-taking"],
    pricing: "Free tier available, Paid from $10/month",
    access: "Web, Integration",
    description: "AI meeting assistant that records, transcribes, and searches across your meetings.",
    url: "https://fireflies.ai",
  },
  {
    name: "v0 by Vercel",
    category: "Coding",
    strengths: ["UI generation","React code","Tailwind CSS","Prototyping"],
    bestFor: ["Web development","UI design","React projects","Prototyping"],
    pricing: "Free tier available, Paid from $20/month",
    access: "Web",
    description: "AI tool that generates React UI components from text descriptions.",
    url: "https://v0.dev",
  },
  {
    name: "Udio",
    category: "Audio",
    strengths: ["Music generation","Custom lyrics","Multiple genres","High quality"],
    bestFor: ["Music creation","Content creation","Background music","Creative projects"],
    pricing: "Free tier available, Paid from $10/month",
    access: "Web",
    description: "AI music generation platform that creates songs from text descriptions.",
    url: "https://www.udio.com",
  },
  {
    name: "Khanmigo (Khan Academy)",
    category: "Education",
    strengths: ["Tutoring","Personalized learning","Multiple subjects","Free"],
    bestFor: ["Students","Homework help","Learning","Test prep"],
    pricing: "$4/month (Khanmigo)",
    access: "Web",
    description: "AI tutor from Khan Academy that provides personalized help across subjects.",
    url: "https://www.khanacademy.org/khan-labs",
  },
  {
    name: "Duolingo Max",
    category: "Education",
    strengths: ["Language learning","AI conversations","Explanations","Gamification"],
    bestFor: ["Language learning","Practice conversations","Grammar explanations","Students"],
    pricing: "From ~$30/month (Max); Super ~$7/month",
    access: "Mobile, Web",
    description: "AI-enhanced language learning with conversation practice and explanations.",
    url: "https://www.duolingo.com",
  },
  {
    name: "ChatPDF",
    category: "Productivity",
    strengths: ["PDF chat","Document analysis","Summaries","Q&A"],
    bestFor: ["Document review","Research","Study","Legal documents"],
    pricing: "Free tier available, Paid from $5/month",
    access: "Web",
    description: "Chat with any PDF document to extract information and get summaries.",
    url: "https://www.chatpdf.com",
  },
  {
    name: "Phind",
    category: "Coding",
    strengths: ["Developer focused","Code search","Explanations","Web access"],
    bestFor: ["Programming questions","Debugging","Code search","Learning"],
    pricing: "Free",
    access: "Web",
    description: "AI search engine specifically designed for developers and programming questions.",
    url: "https://www.phind.com",
  },
  {
    name: "You.com",
    category: "Research",
    strengths: ["AI search","Multiple models","Customizable","Privacy"],
    bestFor: ["Research","Web search","AI chat","Privacy-conscious users"],
    pricing: "Free tier available, Paid from $15/month",
    access: "Web",
    description: "AI-powered search engine with multiple models and customizable experience.",
    url: "https://you.com",
  },
  {
    name: "Limitless (formerly Rewind)",
    category: "Productivity",
    strengths: ["Memory assistant","Screen recording","Search","Privacy"],
    bestFor: ["Personal search","Meeting recall","Research","Productivity"],
    pricing: "Free tier available, Paid from $15/month",
    access: "Desktop app",
    description: "AI memory assistant (formerly Rewind) that records and makes your meetings and screen activity searchable.",
    url: "https://limitless.ai",
  },
  {
    name: "Pi AI",
    category: "General Purpose",
    strengths: ["Emotional support","Personal","Conversational","Free"],
    bestFor: ["Conversation","Brainstorming","Emotional support","Personal assistant"],
    pricing: "Free",
    access: "Web, Mobile",
    description: "Personal AI assistant designed for supportive and meaningful conversations.",
    url: "https://pi.ai",
  },
  {
    name: "Character.AI",
    category: "General Purpose",
    strengths: ["Character chat","Roleplay","Creative","Free"],
    bestFor: ["Entertainment","Creative writing","Roleplay","Character creation"],
    pricing: "Free tier available, Paid from $9/month",
    access: "Web, Mobile",
    description: "Chat with AI characters for entertainment, creativity, and learning.",
    url: "https://character.ai",
  },
  {
    name: "Sora (OpenAI)",
    category: "Video",
    strengths: ["Text-to-video","High quality","Realistic","Long clips"],
    bestFor: ["Video creation","Marketing","Content creation","Storytelling"],
    pricing: "ChatGPT Plus subscription",
    access: "Web",
    description: "OpenAI's text-to-video model that generates realistic videos from descriptions.",
    url: "https://openai.com/sora",
  },
  {
    name: "Poe (Quora)",
    category: "General Purpose",
    strengths: ["Multiple models","Model comparison","Custom bots","Free tier"],
    bestFor: ["Model comparison","Chat","Custom bots","Research"],
    pricing: "Free tier available, Paid from $19/month",
    access: "Web, Mobile",
    description: "Platform to access and compare multiple AI models in one place.",
    url: "https://poe.com",
  },
  {
    name: "Meta AI",
    category: "General Purpose",
    strengths: ["Free","Multimodal","WhatsApp integration","Image generation"],
    bestFor: ["General questions","Image generation","Social media","Free AI"],
    pricing: "Free",
    access: "Web, WhatsApp, Instagram",
    description: "Meta's AI assistant integrated across Facebook, WhatsApp, and Instagram.",
    url: "https://www.meta.ai",
  },
  {
    name: "Remove.bg",
    category: "Image Generation",
    strengths: ["Background removal","Fast","API","Batch processing"],
    bestFor: ["Photo editing","E-commerce","Marketing","Design"],
    pricing: "Free tier available, Pay-per-use",
    access: "Web, API",
    description: "AI tool that automatically removes backgrounds from images.",
    url: "https://www.remove.bg",
  },
  {
    name: "Playground AI",
    category: "Image Generation",
    strengths: ["Free tier","Filters","Canvas","Style variety"],
    bestFor: ["Art creation","Design","Social media","Creative projects"],
    pricing: "Free tier available, Paid from $15/month",
    access: "Web",
    description: "AI image generation platform with canvas editing and style filters.",
    url: "https://playground.com",
  },
  {
    name: "Craiyon",
    category: "Image Generation",
    strengths: ["Free","Unlimited","Simple","No account needed"],
    bestFor: ["Quick images","Ideas","Fun","Experimentation"],
    pricing: "Free",
    access: "Web",
    description: "Free AI image generator that creates images from text with unlimited generations.",
    url: "https://www.craiyon.com",
  },
  {
    name: "ComfyUI",
    category: "Image Generation",
    strengths: ["Open source","Node-based","Customizable","Local"],
    bestFor: ["Advanced users","Custom workflows","Local generation","Research"],
    pricing: "Free",
    access: "Desktop app",
    description: "Open-source node-based interface for Stable Diffusion workflows.",
    url: "https://www.comfy.org",
  },
  {
    name: "Quizlet AI",
    category: "Education",
    strengths: ["Flashcards","Practice tests","Learn mode","AI explanations"],
    bestFor: ["Studying","Exam prep","Memorization","Homework help"],
    pricing: "Free tier available, Paid from $8/month",
    access: "Web, Mobile",
    description: "AI-powered study tool with flashcards, practice tests, and step-by-step homework explanations.",
    url: "https://quizlet.com",
  },
  {
    name: "Zoom AI Companion",
    category: "Productivity",
    strengths: ["Meeting summaries","In-meeting questions","Action items","Smart recordings"],
    bestFor: ["Meetings","Team collaboration","Recap notes"],
    pricing: "Included with paid Zoom plans",
    access: "Zoom app",
    description: "Zoom's built-in AI assistant that summarizes meetings, drafts messages, and answers questions about your meetings.",
    url: "https://www.zoom.com/en/ai-assistant/",
  },
  {
    name: "Calendly AI",
    category: "Business",
    strengths: ["Scheduling","Meeting automation","Routing forms","Reminders"],
    bestFor: ["Booking meetings","Sales calls","Team scheduling"],
    pricing: "Free tier available, Paid from $10/seat/month",
    access: "Web",
    description: "AI-assisted scheduling that finds the best meeting times and automates booking workflows.",
    url: "https://calendly.com",
  }
];
